### ISSUE TITLE
how do i get whats playing? 

### ISSUE THREAD

**Issue by droopified** [haikuginger/kodipydent#11]
really new to this kinda stuff. i tried Player.GetActivePlayers but gives me {'id': '38da4c2856f349f5a358591bdca24539', 'jsonrpc': '2.0', 'result': [{'playerid': 1, 'playertype': 'internal', 'type': 'video'}]}

**Comment by haikuginger** [comment]
It looks like you're on the right track! Once you've looked up the active players on your Kodi device, it [looks like](https://kodi.wiki/view/JSON-RPC_API/v12#Player.GetItem) you can retrieve details about what's going on in a given Player by passing the `playerid` parameter to the `Player.GetItem` method.

**Comment by droopified** [comment]
the only thing i need now is a way to trigger this python script from kodi. i have been trying for a couple of days but cant figure that out. think im giving up...

**Comment by haikuginger** [comment]
I'm afraid I can't help there! I'm going to close this particular issue; feel free to open a new one if you have more questions about using this library!
