### ISSUE TITLE
Won't install using pip on Python 2.7.12

### ISSUE THREAD

**Issue by uvjim** [haikuginger/kodipydent#4]
Hi,

Just gone to try and install v0.3 on my system using pip but it keeps installing v0.2 instead.  According to the logs it isn't compatible with my version of Python (2.7.12).
I can however install directly from GitHub using: -

`pip install git+https://github.com/haikuginger/kodipydent`

I know it should work on that version of Python as that is the version I tested against when submitting the last Pull Request.

Cheers

**Comment by haikuginger** [comment]
Ah, it looks like I neglected to build a universal wheel (compatible with both python2 and python3). I'll have a 0.3.1 release out sometime today with the correct build. Thanks for the heads-up!

**Comment by haikuginger** [comment]
@uvjim, fixed; a python2-compatible wheel is now on PyPI for version 0.3.1; this is the only change for this release.
