### ISSUE TITLE
GetTVShows with filters

### ISSUE THREAD

**Issue by redglory** [haikuginger/kodipydent#6]
Hi, can you give me an example of how to use the "filter" variable for the "GetTVShows" method?

I have:
`kodi_instance = Kodi('192.168.1.77', username='kodi')`

then we would retrieve TVShows on library with:
`kodi_instance.GetTVShows()`

How to filter by label?

Thanks

**Comment by haikuginger** [comment]
@redglory, I'm not sure if you can filter on label - I know you can on tag, though, so that might be what you're looking for.

For any of the items that you can filter on, you can add them to a dictionary and pass it as an argument to the call - as below:

```python
kodi_instance.VideoLibrary.GetTVShows(
    filter={
        'tag': 'mytag',
        'year': 2009,
    }
)
```
