### ISSUE TITLE
Player.Open missing documentation

### ISSUE THREAD

**Issue by himijendrix24** [haikuginger/kodipydent#7]
Hello Jesse and folks,

Not a real issue, rather a documentation-issue.
I want to use your module to start video playback in kodi.
However I can't get it running with the Kodi documentation, which also is not complete:
[https://kodi.wiki/view/JSON-RPC_API/v8#Player](url)

The following code works. I can pause play videos.
```
from kodipydent import Kodi
my_kodi = Kodi('localhost',username='kodi',password='admin')
# PlayPause(playerid[, username, password, play])
my_kodi.Player.PlayPause(playerid=1,username='kodi',password='admin',play='toggle')
```

Now I wan't t open a file but I can't figure out how to pass the filename.

`my_kodi.Player.Open('E:/movies/test.avi')` 
> {'error': {'code': -32602, 'message': 'Invalid params.'},
>  'id': 'b575b10f44734484a64a880a38532c54',
>  'jsonrpc': '2.0'}

`my_kodi.Player.Open(item='E:/movies/test.avi')`
> {'error': {'code': -32602,
  'data': {'method': 'Player.Open',
   'stack': {'message': 'Invalid type string received',
    'name': 'item',
    'type': 'object'}},
  'message': 'Invalid params.'},
 'id': 'e2bc052337a24ef3a82249d78e8f8d4e',
 'jsonrpc': '2.0'} 
 

The parameter scheme of print(my_kodi) says: 

> Open([, username, password, item, options])

How Does it work?

**Comment by haikuginger** [comment]
Hi @himijendrix24, and thanks for the issue!

Stuff like this can be a little bit tricky. In this case, when the JSON-RPC API asks for an "item" object, essentially what it wants is a JSON object that contains enough information to uniquely identify a media item to play. Usually, this is easiest done by pointing to the unique ID of an item in your existing library. An abbreviated example to play a movie is below:

```python
>>> my_kodi = Kodi('localhost')
>>> my_kodi.VideoLibrary.GetMovies()
{'id': 'e7a094962a88496ebf831e05bad9a996', 'jsonrpc': '2.0', 'result': {'limits': {'end': 2, 'start': 0, 'total': 2}, 'movies': [{'label': '(500) Days of Summer', 'movieid': 1}, {'label': '10 Things I Hate About You', 'movieid': 2}]}}
>>> my_kodi.Player.Open(item={'movieid':2})
{'id': 'f6a36c0897c84f768514029e5b2be843', 'jsonrpc': '2.0', 'result': 'OK'}
```

**Comment by himijendrix24** [comment]
Thanks alot for the quick and helpful reply. 
I think I understood the concept now. 
Maybe it would be helpful for absolut JSON novices (like me) to add an example like this to the "How?" section of the repository.

**Comment by himijendrix24** [comment]
### update (for others searching help) ###
actually after trying a little bit more, i think there is alot missing in the json-rpc reference for kodi.

for example i can open a specific file using:
`my_kodi.player.open(item={'file':'/var/media/usbdrive/test.mp4'})`

... while in the reference (api 8) it just says:
_parameters:
    [ mixed item ]
    [ mixed options ]_
fo you would have to figure out what an item consits of.

adding `options={'repeat':'one'}` for looping is accepted, but doesn't work on single files. 
the file would first have to be added to a playlist which in turn can be looped. 

```
my_kodi.playlist.add(0,item={'file':'/var/media/usbdrive/test.mp4'})
my_kodi.player.open(item={'playlistid':0},options={'repeat':'one'})
```

finding out working commands already wasted much of my time and should be explained better in the kodi reference. 
working examples are shared here:
https://forum.kodi.tv/showthread.php?tid=157996&highlight=json
